services:
    guzzle.http_client.class:
        class:  GuzzleHttp\ClientInterface
    jms.serializer.class:
        class:  JMS\Serializer\SerializerInterface
    smoney.base:
        abstract:  true
        arguments: ['%api_base_url%','%api_version%',@guzzle.http_client.class,@jms.serializer.class]
    smoney.user:
        class:  Smoney\Smoney\Client\UserClient
        parent: smoney.base
    smoney.bank.account:
        class:  Smoney\Smoney\Client\BankAccountClient
        parent: smoney.base
    smoney.card.payment:
        class:  Smoney\Smoney\Client\CardPaymentClient
        parent: smoney.base
    smoney.kyc:
        class:  Smoney\Smoney\Client\KycClient
        parent: smoney.base
    smoney.payment:
        class:  Smoney\Smoney\Client\PaymentClient
        parent: smoney.base
    smoney.card.payout:
        class:  Smoney\Smoney\Client\PayoutClient
        parent: smoney.base
    smoney.card.sub.account:
        class:  Smoney\Smoney\Client\SubAccountClient
        parent: smoney.base
